const courseCarousel = [
  {
    img: "./images/images.jfif",
    title: "Front End Web Development",
    mode: "Online",
    duration: "8 Weeks intensive training",
    lessonDuration: "2 Hours / Meeting",
    level: "Intermediate",
    price: "#50,000",
    id: "123",
  },
  {
    img: "./images/fs.png",
    title: "Full Stack Web Development",
    mode: "Online",
    duration: "12 Weeks intensive training",
    lessonDuration: "2 Hours / Meeting",
    level: "Intermediate",
    price: "#120,000",
    id: "456",
  },
  {
    img: "./images/be.png",
    title: "Backend Web Development",
    mode: "Online",
    duration: "8 Weeks intensive training",
    lessonDuration: "2 Hours / Meeting",
    level: "Intermediate",
    price: "#50,000",
    id: "789",
  },
  {
    img: "./images/download.jfif",
    title: "Cyber Security",
    mode: "Online",
    duration: "12 Weeks intensive training",
    lessonDuration: "2 Hours / Meeting",
    level: "Intermediate",
    price: "#120,000",
    id: "012",
  },
  // {
  //   img: "./images/download.jpg",
  //   title: "Full Stack Web Development",
  //   mode: "Online",
  //   duration: "12 Weeks intensive training",
  //   lessonDuration: "2 Hours / Meeting",
  //   level: "Intermediate",
  //   price: "$100",
  // },
  {
    img: "./images/mobile.jfif",
    title: "Mobile App Development",
    mode: "Online",
    duration: "12 Weeks intensive training",
    lessonDuration: "2 Hours / Meeting",
    level: "Intermediate",
    price: "#120,000",
    id: "345",
  },
];

export { courseCarousel };
